apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: layout-transformer
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: gcr.io/ai-customizer-457411/layout-transformer:v1.0
          ports:
            - containerPort: 8081
