apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: layout-transformer
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/ai-customizer-457411/text-to-html-reg/layout-transformer@sha256:d0b9b0f1a8e6f70da4a08c28c71853d6d5bd1b61c5d7cc0ab3df37c0c88291e7
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
